### ISSUE TITLE
Error: isPointerOverScrollbar - arguments: 2 required, 1 given

### ISSUE THREAD

**Issue by movieator** [VickySalunkhe/vs_scrollbar#10]
Hi, after a flutter upgrade a got this error on run:

`vs_scrollbar.dart:317:31: Error: Too few positional arguments: 2 required, 1 given.
    if (isPointerOverScrollbar(event.position)) {`

They added on more argument on isPointerOverScrollbar function (flutter scrollbar widget) as I saw. 

My flutter doctor result:

> [✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-arm, locale el-GR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

Could you fix it please?

Thank you!

**Comment by MajorGrey** [comment]
am also facing this issue

**Comment by VickySalunkhe** [comment]
issue fixed in version 0.2.1 by @jonmountjoy
