### ISSUE TITLE
Flutter 3.12.0: Error: No named parameter with the name 'isAlwaysShown'.

### ISSUE THREAD

**Issue by WieFel** [VickySalunkhe/vs_scrollbar#14]
On Flutter 3.12.0, i get the following error:
```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/vs_scrollbar-0.2.1/lib/vs_scrollbar.dart:143:11: Error: No named parameter with the name 'isAlwaysShown'.
```

It happens because they removed the deprecated param `isAlwaysShown` from `RawScrollbar` (https://api.flutter.dev/flutter/widgets/RawScrollbar/isAlwaysShown.html)

**Comment by barilki** [comment]
same, any updates?

**Comment by WieFel** [comment]
@barilki I just switched to Flutter's integrated `Scrollbar` widget, which can be configured to behave the same as this package. Much easier, no more worries about upgrading.

https://api.flutter.dev/flutter/material/Scrollbar-class.html

**Comment by barilki** [comment]
Thank you, RawScrollbar is exactly what I was looking for.
