### ISSUE TITLE
No named parameter with the name 'isAlwaysShown'.

### ISSUE THREAD

**Issue by 1797890817** [VickySalunkhe/vs_scrollbar#16]
Run project in Flutter 3.13.1，as follow:

[+2710 ms] ../../.pub-cache/hosted/pub.dev/vs_scrollbar-0.2.1/lib/vs_scrollbar.dart:143:11: Error: No named parameter with the name 'isAlwaysShown'.
[        ]           isAlwaysShown: isAlwaysShown,
[        ]           ^^^^^^^^^^^^^
[+1184 ms] ../../.pub-cache/hosted/pub.dev/vs_scrollbar-0.2.1/lib/vs_scrollbar.dart:174:14: Error: The getter 'isAlwaysShown' isn't defined for the class '_MaterialScrollbar'.
[        ]  - '_MaterialScrollbar' is from 'package:vs_scrollbar/vs_scrollbar.dart' ('../../.pub-cache/hosted/pub.dev/vs_scrollbar-0.2.1/lib/vs_scrollbar.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAlwaysShown'.
[        ]       widget.isAlwaysShown ?? _scrollbarTheme.isAlwaysShown ?? false;
[        ]              ^^^^^^^^^^^^^
[        ] ../../.pub-cache/hosted/pub.dev/vs_scrollbar-0.2.1/lib/vs_scrollbar.dart:174:47: Error: The getter 'isAlwaysShown' isn't defined for the class 'ScrollbarThemeData'.
[        ]  - 'ScrollbarThemeData' is from 'package:flutter/src/material/scrollbar_theme.dart' ('../../GreenSoft/flutter/packages/flutter/lib/src/material/scrollbar_theme.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAlwaysShown'.
[        ]       widget.isAlwaysShown ?? _scrollbarTheme.isAlwaysShown ?? false;
[        ]                                               ^^^^^^^^^^^^^

**Comment by VickySalunkhe** [comment]
Fixed in the latest update v1.0.0
