### ISSUE TITLE
[Feature request] Support duration customization

### ISSUE THREAD

**Issue by narumi147** [VickySalunkhe/vs_scrollbar#3]
Just add a property which default to `_kScrollbarTimeToFade`, the default duration 0.6s is too short if I use touchpad and want to catch the scrollbar.

**Comment by VickySalunkhe** [comment]
@narumishi will surely add that, thank you for sharing.
Plz do like the package on pub.dev and star the repository it will help others people too. Thank you :)

**Comment by VickySalunkhe** [comment]
added support in the new version of the package.
