### ISSUE TITLE
Disable horizontal drag for vertical scroll views, vice verse

### ISSUE THREAD

**Issue by narumi147** [VickySalunkhe/vs_scrollbar#4]
For example, the default scroll direction of `ListView` is vertical, and shouldn't response to horizontal drag event, but it did. 

A ideal solution is check the scroll direction of child, I have no idea about that. 
Another simple solution is split `allowDrag` param into `allowVerticalDrag=true` and `allowHorizontalDrag=false`.

**Comment by VickySalunkhe** [comment]
Thank you for the feedback :)
Have added a field `scrollDirection` which will handle the use-case you mentioned above.

New changes have been published.

**Comment by narumi147** [comment]
Thanks for your quick fix. 

And a small advice, is it better that `Axis.vetical` becomes the default value of `scrollDirection`? Since mostly used widget like `ListView` and `GridView` use the vertical as default.

**Comment by VickySalunkhe** [comment]
> Thanks for your quick fix.
> 
> And a small advice, is it better that `Axis.vetical` becomes the default value of `scrollDirection`? Since mostly used widget like `ListView` and `GridView` use the vertical as default.

I thought about this case
but if kept Axis.vertical as default
and suppose if the user doesn't provide any value to scrollDirection
then the drag behaviour will behave weirdly which is the main point you highlighted above.
so thought about this approach

to enable drag, the user needs to provide `Axis` else only drag functionality will not work, which is fine as this causes no problems in the package, and general use-case if also taken care of.

**Comment by narumi147** [comment]
Your decision is right, it is more safe. 👍
