### ISSUE TITLE
reverse: true breaks the horizontal scrollbar

### ISSUE THREAD

**Issue by jakebonk** [VickySalunkhe/vs_scrollbar#6]
When setting a ListView to have reverse:true the scrollbar becomes unusable. I didn't test it with a vertical ListView but it won't work with a horizontal one.

**Comment by deepbluev7** [comment]
It also causes issues with the vertical scrollbar, where dragging works exactly reverse of what you would expect. The bar is positioned correctly, but the drag area is positioned in a mirrored position.

**Comment by VickySalunkhe** [comment]
Fixed the issue in the latest package, with few breaking changes, 
Also, the Package is Migrated to dart Sound Null Safety.

Now functionality like drag is supported by default and works when the `ScrollController `object is passed.

upgrade the package to 0.2.0 to enjoy the upgrade.

Thank you for using VsScrollbar.

**Comment by deepbluev7** [comment]
Awesome, thank you!
