### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by nipunasudha** [VickySalunkhe/vs_scrollbar#7]
Could you please upgrade the package for null safety?

**Comment by VickySalunkhe** [comment]
Added null safety to the latest package, with few breaking changes, 
upgrade the package to 0.2.0 to enjoy the upgrade.
Thank you for using VsScrollbar.

**Comment by nipunasudha** [comment]
Thank you @VickySalunkhe Your time & effort is much appreciated!
