### ISSUE TITLE
Change track size

### ISSUE THREAD

**Issue by dhruv048** [VickySalunkhe/vs_scrollbar#8]
Hey, thanks for the awesome package.

it would be great if we could change scrollbar track size just like in the image.
![Inked98ca7bac-b111-4ee9-bb8d-d17873713e90_LI](https://user-images.githubusercontent.com/52712358/117445509-7a609700-af5a-11eb-8ab2-b3a68d8803b3.jpg)

Thanks.

**Comment by VickySalunkhe** [comment]
Hi, @dhruv048 scrollbar track size is dynamic mainly dependant upon the length of the array passed.
Adjusting it manually will break the preset method for dynamic sizing according to generated list.
